# Builds using maven
---
name: Maven

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 17 * * 0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Repository
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
      - name: Deploy
        run: ./deploy.sh
        env:
          WIKI_UPLOAD_PASS: ${{ secrets.BF_WIKI_UPLOAD_PASS }}
